export const SEMANTIC_FLOW_MIN_HOLD_MS = 850;
export const SEMANTIC_FLOW_COALESCE_MS = 140;
export const SEMANTIC_FLOW_LIVE_MIN_HOLD_MS = 360;
export const SEMANTIC_FLOW_LIVE_COALESCE_MS = 70;

export const SEMANTIC_FLOW_LEAVE_MS = 240;
export const SEMANTIC_FLOW_ENTER_MS = 480;
export const SEMANTIC_FLOW_LIVE_LEAVE_MS = 110;
export const SEMANTIC_FLOW_LIVE_ENTER_MS = 220;
