export {
	AGENT_HTTP_PROXY_ENV_FLAG,
	isAgentHttpProxyEnabled,
	shouldAutoEnableAgentHttpProxy,
	parseConnectAuthority,
	decideProxyHost,
	startAgentHttpProxy,
	ensureAgentHttpProxy,
	stopAgentHttpProxy,
	getAgentHttpProxyInfo,
	applyAgentProxyEnv,
	getProxyAuditLog,
	clearProxyAuditLog,
	setProxyAuditCapacity,
	type HostEvaluator,
	type AgentHttpProxyInfo,
	type StartAgentHttpProxyOptions,
	type ProxyAuditEntry,
} from "./agent-http-proxy.js";
