// Core session management

// Config paths
export { getAgentDir, VERSION } from "./config.js";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.js";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.js";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.js";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.js";
export type {
	CollaborationModeKind,
	PlanSessionEvent,
	PlanStep,
	PlanStepStatus,
	RequestUserInputAnswer,
	RequestUserInputArgs,
	RequestUserInputOption,
	RequestUserInputQuestion,
	RequestUserInputResponse,
	UpdatePlanArgs,
} from "./core/plan-protocol.js";
// Extension system
export type {
	AgentEndEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageRenderer,
	MessageRenderOptions,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WriteToolCallEvent,
} from "./core/extensions/index.js";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.js";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.js";
export { convertToLlm } from "./core/messages.js";
export { ModelRegistry } from "./core/model-registry.js";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.js";
export { DefaultPackageManager } from "./core/package-manager.js";
export type { ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./core/resource-loader.js";
export { DefaultResourceLoader } from "./core/resource-loader.js";
// SDK for programmatic usage
export {
	type AgentSessionRuntimeBootstrap,
	AgentSessionRuntimeHost,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeOptions,
	// Factory
	createAgentSession,
	createAgentSessionRuntime,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createWriteTool,
	type PromptTemplate,
	// Pre-built tools (use process.cwd())
	readOnlyTools,
} from "./core/sdk.js";
export {
	type BenchmarkResult,
	type CreateImprovementTaskInput,
	type GovernorCheckResult,
	type ImprovementAttempt,
	type ImprovementBudget,
	type ImprovementTask,
	type ImprovementTaskKind,
	type ImprovementTaskStatus,
	type RecordBenchmarkResultInput,
	type ScoreboardSummary,
	SelfImprovementGovernor,
	SelfImprovementLedger,
	type SelfImprovementLedgerEntry,
	SelfImprovementOrchestrator,
	type SelfImprovementOrchestratorOptions,
	SelfImprovementScoreboard,
	type SelfImprovementState,
	type SuiteMetrics,
} from "./core/self-improvement/index.js";
export {
	type BranchSummaryEntry,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.js";
export {
	type CompactionSettings,
	type ImageSettings,
	type PackageSource,
	type RetrySettings,
	SettingsManager,
} from "./core/settings-manager.js";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.js";
export { createSyntheticSourceInfo } from "./core/source-info.js";
// Codex-aligned approval / guardian (presets + session accept + durable always)
export {
	builtinApprovalPresets,
	guardianRuntime,
	setGlobalApprovalEmitter,
	setGuardianInterruptHook,
	gateToolExecution,
	DEFAULT_DENIAL_CIRCUIT_BREAKER,
	// Durable guardian always-allows (S-TRUST.1)
	configureGuardianAlwaysStore,
	loadDurableGuardianAllows,
	listDurableGuardianAllows,
	clearDurableGuardianAllows,
	removeGuardianAlwaysCommandKey,
	removeGuardianAlwaysPrefix,
	removeGuardianAlwaysHost,
	flushGuardianAlwaysWrites,
	rememberGuardianAlwaysCommandKey,
	rememberGuardianAlwaysPrefix,
	rememberGuardianAlwaysHost,
	defaultGuardianAlwaysPath,
	getGuardianAlwaysStorePath,
	type ApprovalDecision,
	type ApprovalKind,
	type ApprovalPreset,
	type ApprovalRequest,
	type ApprovalResponse,
	type ApprovalTrailEntry,
	type AskForApproval,
	type ToolGateResult,
	type GuardianDurableSnapshot,
	type GuardianDurableHosts,
} from "./core/guardian/index.js";
export {
	turnDiffAggregator,
	splitApplyPatchToFileDiffs,
	rebuildTurnDiffFromDetails,
	rebuildTurnDiffFromSessionEntries,
	rebuildAllTurnDiffsFromBranch,
	serializeTurnDiffSnapshot,
	serializeTurnDiffSnapshotForHistory,
	deserializeTurnDiffSnapshot,
	type TurnDiffSnapshot,
	type TurnFileDiffEntry,
	type TurnFileChangeKind,
	type TurnDiffHistoryEntry,
} from "./core/turn-diff/index.js";
export {
	assertOsSandboxAllowsSpawn,
	getOsSandboxBackend,
	setOsSandboxBackend,
	resolveOsSandboxBackend,
	resolveOsSandboxBackendAsync,
	ensureOsSandboxBackend,
	resolveOsSandboxMode,
	resolveOsSandboxHelperPath,
	resolveOsSandboxHelperSpawn,
	probeOsSandboxHelper,
	clearOsSandboxProbeCache,
	HostSpawnBackend,
	ExperimentalOsSandboxBackend,
	ExternalRunnerOsSandboxBackend,
	OS_SANDBOX_PROBE_ARG,
	OS_SANDBOX_PROBE_TIMEOUT_MS,
	parseOsSandboxHelperResponse,
	serializeOsSandboxEnv,
	type OsSandboxBackend,
	type OsSandboxExecRequest,
	type OsSandboxExecResult,
	type OsSandboxMode,
	type OsSandboxHelperRequest,
	type OsSandboxHelperResponse,
} from "./core/sandbox/index.js";
export {
	sessionNetworkPolicy,
	extractNetworkTargets,
	normalizeHost,
	// S-NET.1 durable host policy
	configureDurableNetworkHostsPath,
	loadDurableNetworkHosts,
	saveDurableNetworkHosts,
	allowDurableHost,
	denyDurableHost,
	listDurableNetworkHosts,
	removeDurableHost,
	clearDurableNetworkHosts,
	flushDurableNetworkHostsWrites,
	getDurableNetworkHostsPath,
	getDefaultDurableNetworkHostsPath,
	isDurableHostAllowed,
	isDurableHostDenied,
	resetDurableNetworkHostsForTests,
	wireNetworkPolicyChecker,
	type ExtractedNetworkTarget,
	type DurableNetworkHostsSnapshot,
	type DurableHostChecker,
} from "./core/network-policy/index.js";
export {
	AGENT_HTTP_PROXY_ENV_FLAG,
	isAgentHttpProxyEnabled,
	shouldAutoEnableAgentHttpProxy,
	ensureAgentHttpProxy,
	startAgentHttpProxy,
	stopAgentHttpProxy,
	getAgentHttpProxyInfo,
	applyAgentProxyEnv,
	getProxyAuditLog,
	clearProxyAuditLog,
	setProxyAuditCapacity,
	type AgentHttpProxyInfo,
	type ProxyAuditEntry,
} from "./core/network-proxy/index.js";
export {
	turnLifecycle,
	TurnLifecycle,
	type TurnAbortReason,
	type TurnPhase,
	type TurnLifecycleEvent,
} from "./core/turn/index.js";
export {
	setPlanUpdateListener,
	publishPlanUpdate,
	getLastPlanUpdate,
	clearLastPlanUpdate,
} from "./core/plan-update-bus.js";
export {
	createUpdatePlanToolDefinition,
	updatePlanTool,
	updatePlanToolDefinition,
} from "./core/tools/update-plan.js";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	bashTool,
	bashToolDefinition,
	codingTools,
	createBashToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLsToolDefinition,
	createReadToolDefinition,
	createWriteToolDefinition,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	editTool,
	editToolDefinition,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	findTool,
	findToolDefinition,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	grepTool,
	grepToolDefinition,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	lsTool,
	lsToolDefinition,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	readTool,
	readToolDefinition,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
	writeTool,
	writeToolDefinition,
} from "./core/tools/index.js";
// Main entry point
export { main } from "./main.js";
// Run modes for programmatic SDK usage
export {
	InteractiveMode,
	type InteractiveModeOptions,
	type PrintModeOptions,
	runPrintMode,
	runRpcMode,
} from "./modes/index.js";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.js";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.js";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.js";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.js";
// Shell utilities
export { getShellConfig } from "./utils/shell.js";
